server:
  port: 9003

spring:
  application:
    name: books-service
  datasource:
    url: jdbc:mysql://localhost:3306/books?createDatabaseIfNotExist=true
    username: root
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true